---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530 # v1.38.0
    hooks:
      - id: yamllint
        args: [--strict]
        exclude: ^(cluster/apps/example/base/deployment\.yaml$|cluster/flux-system/gotk-components\.yaml$)

  - repo: https://github.com/rhysd/actionlint
    rev: 914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12
    hooks:
      - id: actionlint-system

  - repo: local
    hooks:
      - id: tofu-fmt
        name: tofu fmt
        entry: tofu fmt -check -recursive
        language: system
        pass_filenames: false
        files: \.tf$

      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
