---
all:
  vars:
    ansible_user: ops
    ansible_become: true
    wireguard_interface: wg0
    wireguard_port: 51820
    wireguard_peers_group: wireguard
    k3s_cluster_init_host: ""
    k3s_server_host: ""
  children:
    wireguard:
      hosts: {}
    k3s_servers:
      hosts: {}
    k3s_agents:
      hosts: {}
    storage_stateful:
      hosts: {}
    ingress:
      hosts: {}

...
